# Generated by Django 4.2.3 on 2023-08-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(choices=[(0, 'Free'), (500, 'Bronze'), (1000, 'Silver'), (5000, 'Gold')])),
                ('reward', models.CharField(max_length=200)),
            ],
        ),
    ]
