# Generated by Django 4.2.3 on 2023-08-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accountlevel_amount_accountlevel_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlevel',
            name='reward',
            field=models.CharField(max_length=150),
        ),
    ]
