# Generated by Django 4.2.3 on 2023-08-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fundshubuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundshubuser',
            name='account_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountlevel'),
        ),
    ]
