# Generated by Django 4.2.3 on 2023-08-03 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountlevel_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlevel',
            name='max_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9223372036854775807)]),
        ),
        migrations.AlterField(
            model_name='accountlevel',
            name='min_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
