# Generated by Django 4.2.3 on 2023-08-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_fundshubuser_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundshubuser',
            name='account_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountlevel'),
        ),
    ]
