# Generated by Django 4.2.3 on 2023-08-03 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fundsHub.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountlevel_max_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), fundsHub.accounts.validators.start_with_letter])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), fundsHub.accounts.validators.start_with_letter])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='assets/profile_pictures/')),
                ('account_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accountlevel')),
            ],
        ),
    ]
