# Generated by Django 4.2.3 on 2023-08-12 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fundshubuser_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundshubuser',
            name='amount_donated',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
