# Generated by Django 4.2.3 on 2023-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fundshubuser_amount_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundshubuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
