# Generated by Django 4.2.3 on 2023-08-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fundshubuser_user_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundshubuser',
            name='user_projects',
        ),
    ]
