# Generated by Django 4.2.3 on 2023-08-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_fundshubuser_account_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundshubuser',
            name='account_level',
        ),
    ]
