# Generated by Django 4.2.3 on 2023-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_fundshubuser_account_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountlevel',
            options={'ordering': ['min_amount']},
        ),
        migrations.AlterField(
            model_name='accountlevel',
            name='max_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='accountlevel',
            name='min_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='accountlevel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fundshubuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/portrait_placeholder.png', upload_to='profile_pictures/'),
        ),
    ]
