# Generated by Django 4.2.3 on 2023-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_accountlevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundshubuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
