# Generated by Django 4.2.3 on 2023-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_fundshubuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlevel',
            name='max_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
