# Generated by Django 4.2.3 on 2023-08-06 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='assets/projects_pictures/')),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('long_description', models.TextField()),
                ('project_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCompleteness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9223372036854775807)])),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Project Completeness',
            },
        ),
    ]
