# Generated by Django 4.2.3 on 2023-08-13 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_userprojects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjects',
            new_name='UserProject',
        ),
    ]
