# Generated by Django 4.2.3 on 2023-08-03 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_alter_project_project_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCompleteness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Project Completeness',
            },
        ),
    ]
