# Generated by Django 4.2.3 on 2023-08-13 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_fundshubuser_user_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_rename_userprojects_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
