# Generated by Django 4.2.3 on 2023-08-03 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectcompleteness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcompleteness',
            name='percentage',
        ),
        migrations.AddField(
            model_name='projectcompleteness',
            name='max_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9223372036854775807)]),
        ),
        migrations.AddField(
            model_name='projectcompleteness',
            name='min_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
