# Generated by Django 4.2.3 on 2023-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectcompleteness_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(upload_to='assets/projects_pictures/'),
        ),
        migrations.AlterField(
            model_name='projectcompleteness',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
