# Generated by Django 4.2.3 on 2023-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
