# Generated by Django 4.2.3 on 2023-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_project_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
